### ISSUE TITLE
Wrong syntax for SQL comments cause errors on restore

### ISSUE THREAD

**Issue by ivangretsky** [ryancramerdesign/ProcessDatabaseBackups#1]
I get errors while manually restoring backups generated by the module. It seems like the 1st and last lines, generated by the module use wrong syntax for MySQL [comments](http://dev.mysql.com/doc/refman/5.0/en/comments.html).
It should be --, not ---.

**Comment by ryancramerdesign** [comment]
The files are core generated rather than by this module. But I ran into the same issue a couple of weeks ago. A recent update (to the core) switches it to `# ---` which seems to make it friendly with importing elsewhere. I suppose we could do the `--` instead, but was trying to differentiate from a regular MySQL comment as much as possible.
